eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

server:
  port: 8763

spring:
  application:
    name: service-feign

feign:
  hystrix:
    enabled=true: