server:
  port: 8770

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/hibiup/SpringCloudExamples/
        searchPaths: configure
        username:
        password: