server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/hibiup/SpringCloudConfig/
        searchPaths: respo
        username:
        password: