# This is for this application, not for Eureka server
server:
  port: 8772

spring:
  application:
    name: service-backend
  zipkin:
    # 配置 zipkin，支持 service trace
    base-url: http://192.168.56.110:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  instance:
    hostname: localhost
    port: 8761   # Eureka server's port

