## ????
# actuator ???(?? spring-boot-starter-actuator)
management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

# resilience4j
feign:
  client:
    config:
      httpBinClient:
        read-timeout: 2000
        connect-timeout: 1000
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      HttpBinClient_getBinWithDelayInSeconds_int:
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
  timelimiter:
    configs:
      default:
        timeoutDuration: 20s