server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    # 默认情况下erureka server也是一个eureka client ,必须要指定一个 server。
    # 通过 eureka.client.registerWithEureka：false
    # 和 fetchRegistry：false 来表明自己是一个 eureka server.
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server
