# This is for this application, not for Eureka server
#server:
#  port: 8762

spring:
  application:
    name: service-hello

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  instance:
    hostname: localhost
    port: 8761   # Eureka server's port
