server:
    port: 8762

eureka:
    instance:
        hostname: localhost
        port: 8761
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                native:
                    searchLocations: "[classpath:/, classpath:/config, classpath:/config/{application}, classpath:/config/{application}/{profile}]"
                git:
                    default-label: master
                    clone-on-start: true
                    # ignore-local-ssh-settings=false: User local ssh settings
                    ignore-local-ssh-settings: false
                    # Or, if ignore-local-ssh-settings=false, copy and past private key here:
                    private-key: |
                        -----BEGIN OPENSSH PRIVATE KEY-----
                        ...
                        -----END OPENSSH PRIVATE KEY-----
                    # ?? application name
                    repos:
                        # Example 1: ? config-service ????????
                        # Repository URL ????: http://root:s3cr3t@localhost:${server.port}/{application}/{profile}/[label]/[path/to/file_name]
                        config-service-dev:
                            # curl http://root:s3cr3t@localhost:${server.port}/config-service/[dev|development]/[main|develop]
                            # pattern ?????
                            #  1. ?? uri?
                            #  2. ?? uri ?????application=config-service; profile=[dev|development]; label=[main|master|...]
                            pattern:
                                - 'config-service/development'     # ???? development/application.properties
                                - 'config-service/dev'             # ???? development/application.properties; development/application-dev.properties
                            uri: git@github.com:hibiup/SpringCloudExamples.git
                            search-paths:
                                - 'config-repo/{application}/{profile}'    # ???????? application=config-service; profile=[dev|development]
                                - 'config-repo/{application}/development'  # ??????????? profile ???? `dev`?
                            force-pull: true                 # ??????????? pull ???? cache ??????????????Default is false
                        config-service-staging:
                            # curl http://root:s3cr3t@localhost:8888/config-service/[qa|staging]/[main|develop]
                            pattern:
                                - 'config-service/qa'             # ?????development/application.properties; development/application-qa.properties;
                                - 'config-service/staging'        # ?????development/application.properties; development/application-staging.properties;
                            uri: git@github.com:hibiup/SpringCloudExamples.git
                            search-paths:
                                - 'config-repo/{application}{profile}'    # ??
                                - 'config-repo/{application}/staging'
                            force-pull: true
                        config-service-production:
                            # curl http://root:s3cr3t@localhost:8888/config-service/prod/[main|develop]
                            pattern:
                                - 'config-service/prod'          # ???? development/application.properties
                            uri: git@github.com:hibiup/SpringCloudExamples.git
                            search-paths:
                                - 'config-repo/{application}/production'
                            force-pull: true

                        # Example2? ???*??????
                        # ?????????????? repository ???????????????
                        other-application:
                            # curl http://root:s3cr3t@localhost:8888/<app_name>/[dev|development]
                            # {application} ?????? uri ???? app_name
                            # {profile} = [dev|qa|prod]
                            # {label} = default as main|master
                            pattern:
                                - '*/dev/*'
                                - '*/qa/*'
                                - '*/prod/*'
                            uri: git@github.com:hibiup/SpringCloudExamples.git  # ??git@github.com:hibiup/{application}.git
                            search-paths: 'config-repo/{application}/{profile}'
                            force-pull: true

                        local:
                            pattern: local*
                            uri: file:${user.home}/mycode/java/SpringCloudConfigExample/config-repo/config-service

                    # ?? uri: http://localhost:8762/config-service/default
                    # ???? repos ?????????????????production?
                    uri: git@github.com:hibiup/SpringCloudExamples.git
                    search-paths:
                        - 'config-repo/{application}/production'
                    force-pull: true  # Update local cache every time when server is starting